import Head from "next/head";
import { type NextPage } from "next";

import UserSidebar from "@layouts/user-sidebar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sommunity</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <UserSidebar />
      </main>
    </>
  );
};

export default Home;
